--- 
- 
  hosts: all
  tasks: 
    - 
      copy: 
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA3nH7GoSh8tRen298Sn4qfycM1jfYum7GyoHheUrea26p7q7bIh3g3ouUaj5pRYjgVWoTqnHBaawGJVlhPskTPMJ7do80+ZnZLk8I8EhXk7Un8dt4gJJPtyxFPKlWkz3kM6Ue0TWKY/V9m0bxBd5azGTzUpIt1JduS7gnT+LGpnJeHwGHBVAloP5Pc9j9vaJ6CldTZL2lp31ZAOYLkmme4fpja0caRUDcCeq0qZPNFyuEm+Fey1Wx51a7pBiHP6xPlXgN1Abq0M5YXqxME36WidBeQEbkVfGvTJiF7ldYFgywqCgTXW31ZBwbDre7n/rhhEfnY4I4MJQKDidr095j jenkins@ip-172-31-2-204
        dest: /usr/local/logstash/cert.crt
      name: "Copy Crt"
    - 
      copy: 
        content: |
            input {
              kafka
                {
                  bootstrap_servers => "43.205.18.44:9092"
                  topics => "demo-topic"
                  codec => json
              }
            }
            output {
              elasticsearch {
                hosts => ["15.207.72.92:9200"]
                index => "ttt-mb-%{+YYYY.ww}"
                user => "kibanaadmin"
                password => "sandeep"
                cacert => "/usr/local/logstash/cert.crt"
                ssl => true
                ssl_certificate_verification => false
              }
            }
        dest: /usr/local/logstash/config/logstash-kafka.conf
      name: "Creating a logstash conf"
